# -*- coding: utf-8 -*-
# Codes are at the end of the page
__author__ = 'HamdiBurak'

import tweepy
import csv
import urlparse

seslenisKelimeleri ={ 'positive' : [
    "aşkım",
    "sonsuzlugum",
    "herşeyim",
    "geleceğim",
    "erkeğim",
    "kadınım",
    "sevdiğim",
    "paşam",
    "prensesim",
    "Askim",
    "Birtanem",
    "hayatim",
    "ömrüm",
    "Yakisiklim",
    "tek gerçeğim",
    "yaşama sebebim",
    "nefesim",
    "ömrüm",
    "hayatımın anlamı",
    "böceğim",
    "canım",
    "sevgilim",
    "tatlım",
    'birtanem',
    "gülüm",
], 'negative' : [
    "kardeşim",
    "aslan",
    "bacım",
    "ablam",
    "abla",
    "kanka",
    "Adamım",
    "aga",
    "ajan",
    "arkadaşım",
    "başkan",
    "birader",
    "devrem",
    "dostum",
    "gakko",
    "gözüm",
    "iki gözüm",
    "hacı",
    "hocam",
    "kanki",
    "kardo",
    "gada",
    "keke",
    "kirve",
    "kızan",
    "kurban",
    "kuzum",
    "moruk",
    "pampa",
    "reis",
    "toprağım",
    "azizim",
    "üstadım",
    "usta",
    "mübarek",
<<<<<<< HEAD
    "köpeğim",
    "git",
=======
>>>>>>> origin/master


    "sus",
    "yeter",
    "aynen",
    "hayır",
    "olmaz",
]}

sifatlar = {
    'positive': [
    "afacanlık",
    "afiyet",
    "aktif",
    "alkol",
    "babalık",
    "bağımsız",
    "balo",
<<<<<<< HEAD
    "var",
    "olamaz",
=======
>>>>>>> origin/master
    "bar",
    "bekleyiş",
    "bellek",
    "bilgili",
    "börtü",
    "bütünleşme",
    "canlandırıcı",
    "canlısı",
    "düşünsel",
    "eğlendirici",
    "eksiklik",
    "emniyet",
    "empati",
    "eser",
    "etkileyici",
    "ezgi",
    "fedakar",
    "festival",
    "forum",
    "gerçeklik",
    "gereksinim",
    "girişken",
    "gizlilik",
    "güçlülük",
    "güler",
    "hoşluk",
    "imkan",
    "ironi",
    "ıslak",
    "iyiliksever",
    "izin",
    "kader",
    "katılım",
    "kavram",
    "kavuşma",
    "kıymet",
    "kocaman",
    "kokulu",
    "kolaylık",
    "kutlama",
    "kutsal",
    "kuvvetli",
    "mesut",
    "motivasyon",
    "mütevazi",
    "mütevazilik",
    "naif",
    "narin",
    "nemli",
    "nitelik",
    "nur",
    "oğul",
    "okşama",
    "olmak",
    "ortak",
    "öykü",
    "parti",
    "performans",
    "problem",
    "reklam",
    "sabah",
    "sağlamlık",
    "şakacı",
    "sebat",
    "şeker",
    "serüven",
    "sevimlilik",
    "sevinmek",
    "seyran",
    "sıcacık",
    "sığınma",
    "sır",
    "sportif",
    "standart",
    "tabiat",
    "tarife",
    "temsil",
    "terbiye",
    "ufak",
    "uğraş",
    "uğur",
    "uğurlu",
    "üretken",
    "zengin",
    "zeki",
    "zararsız",
    "yiğit",
    "yetkili",
    "yenilmez",
    "yenilikçi",
    "yaratıcı",
    "yakışıklı",
    "üstünlük",
    "vicdanlı",
    "verimli",
    "varlıklı",
    "uyumlu",
    "uysal",
    "uygar",
    "usta",
    "üretken",
    "umutlu",
    "uğurlu",
    "tutkulu",
    "tutarlı",
    "tertemiz",
    "temkinli",
    "tatlı",
    "tamahkâr",
    "suçsuz",
    "sosyal",
    "şevkli",
    "sevimli",
    "sevilen",
    "sempatik",
    "seksi",
    "sebatlı",
    "saygılı",
    "uyanıklık",
    "şanslı",
    "samimi",
    "şamatalı",
    "sakinleşmiş",
    "sağlıklı",
    "sağgörülü",
    "sağduyulu",
    "saf",
    "sadık",
    "rahat",
    "radikal",
    "prestijli",
    "özverili",
    "oturaklı",
    "otoriter",
    "önemli",
    "olgun",
    "ölçülü",
    "olağanüstü",
    "okumuş",
    "öğretici",
    "nükteli",
    "nostaljik",
    "nitelikli",
    "neşeli",
    "nazik",
    "mutlu",
    "müthiş",
    "müşfik",
    "mükemmel",
    "misafirperver",
    "minnettar",
    "mert",
    "merhametli",
    "marjinal",
    "marifetli",
    "mantıklı",
    "mağrur",
    "maceraperest",
    "kusursuz",
    "kültürlü",
    "kibar",
    "kararlı",
    "kanaatkâr",
    "iyimser",
    "iyiliksever",
    "itibarlı",
    "itaatkâr",
    "vakit",
    "iradeli",
    "ihtiyatlı",
    "iffetli",
    "içten",
    "huzurlu",
    "hürmetkâr",
    "heybetli",
    "hevesli",
    "hayırsever",
    "güvenilir",
    "güçlü",
    "gözükara",
    "gösterişli",
    "girişken",
    "gerçekçi",
    "etkileyici",
    "varoluş",
    "entellektüel",
    "düzenli",
    "duygusal",
    "düşünceli",
    "dürüst",
    "disiplinli",
    "dinlenmiş",
    "dinç",
    "dinamik",
    "dikkatli",
    "destekli",
    "destekleyici",
    "dengeli",
    "deneyimli",
    "dayanıklı",
    "coşkulu",
    "cömert",
    "çevik",
    "cesur",
    "çekici",
    "canlanmış",
    "çalışkan",
    "vefalı",
    "bilinçli",
    "becerikli",
    "asil",
    "arzulu",
    "anlayışlı",
    "alımlı",
    "alçakgönüllü",
    "veren",
    "yalın",
    "bütünleşme",
    "canlandırıcı",
    "canlısı",
    "düşünsel",
    "eğlendirici",
    "eksiklik",
    "emniyet",
    "empati",
    "entellektüel",
    "eser",
    "etkileyici",
    "ezgi",
    "fedakar",
    "festival",
    "forum",
    "gerçeklik",
    "gereksinim",
    "girişken",
    "gizlilik",
    "gözlük",
    "güçlülük",
    "güler",
    "hoşluk",
    "imkan",
    "ironi",
    "ıslak",
    "iyiliksever",
    "izin",
    "kader",
    "katılım",
    "kavram",
    "kavuşma",
    "kıymet",
    "kocaman",
    "kokulu",
    "kolaylık",
    "kutlama",
    "kutsal",
    "kuvvetli",
    "mesut",
    "motivasyon",
    "mütevazi",
    "mütevazı",
    "mütevazilik",
    "naif",
    "narin",
    "nemli",
    "nitelik",
    "nur",
    "oğul",
    "okşama",
    "olmak",
    "ortak",
    "öykü",
    "parti",
    "performans",
    "problem",
    "sabah",
    "sağlamlık",
    "şakacı",
    "sebat",
    "şeker",
    "serüven",
    "sevimlilik",
    "sevinmek",
    "seyran",
    "sıcacık",
    "sığınma",
    "sportif",
    "terbiye",
    "uğur",
    "uğurlu",
    "üretken",
    "zengin",
    "zeki",
    "zararsız",
    "yiğit",
    "yenilmez",
    "yenilikçi",
    "yaratıcı",
    "yakışıklı",
    "üstünlük",
    "vicdanlı",
    "verimli",
    "varlıklı",
    "uyumlu",
    "uysal",
    "uygar",
    "usta",
    "üretken",
    "umutlu",
    "uğurlu",
    "tutkulu",
    "tutarlı",
    "tertemiz",
    "temkinli",
    "tatlı",
    "tamahkâr",
    "suçsuz",
    "sosyal",
    "şevkli",
    "sevimli",
    "sevilen",
    "sempatik",
    "seksi",
    "sebatlı",
    "saygılı",
    "uyanıklık",
    "şanslı",
    "samimi",
    "sakinleşmiş",
    "sağlıklı",
    "sağgörülü",
    "sağduyulu",
    "saf",
    "sadık",
    "rahat",
    "radikal",
    "prestijli",
    "özverili",
    "oturaklı",
    "otoriter",
    "önemli",
    "olgun",
    "ölçülü",
    "olağanüstü",
    "okumuş",
    "öğretici",
    "nükteli",
    "nostaljik",
    "nitelikli",
    "neşeli",
    "nazik",
    "mutlu",
    "müthiş",
    "müşfik",
    "mükemmel",
    "misafirperver",
    "minnettar",


], 'negative': [
    "yargı",
    "yoksul",
    "ekşime",
    "fena",
    "fena",
    "garip",
    "gereksiz",
    "ilkel",
    "kabızlık",
    "korkunç",
    "müstehcen",
    "mutsuz",
    "şişkinlik",
    "uykusuz",
    "yavan",
    "yorucu",
    "yağma",
    "entellektüel",
    "gözlük",
    "Züppe",
    "zorba",
    "zayıf",
    "zararlı",
    "yorgun",
    "yoksun",
    "yoğun",
    "yırtıcı",
    "yılgın",
    "yıkıcı",
    "yaşlı",
    "Yargılayıcı",
    "yaramaz",
    "yaralı",
    "yapmacık",
    "yapayalnız",
    "yaltakçı",
    "yalnız",
    "yalaka",
    "verimsiz",
    "vefasız",
    "vahşi",
    "üzücü",
    "üzgün",
    "uzak",
    "uyumsuz",
    "utangaç",
    "üşütük",
    "üşengeç",
    "ürkek",
    "unutkan",
    "umutsuz",
    "uğursuz",
    "uçarı",
    "tutarsız",
    "tükenmiş",
    "terbiyesiz",
    "tepkili",
    "tehlikeli",
    "tehditkâr",
    "tedirgin",
    "suratsız",
    "şüpheli",
    "şüpheci",
    "spastik",
    "sömürücü",
    "sırnaşık",
    "şımartılmış",
    "sıkışmış",
    "sıkıntılı",
    "sığ",
<<<<<<< HEAD
    "sübyancı",
=======
>>>>>>> origin/master
    "sinsi",
    "sinirli",
    "şeytani",
    "sevgisiz",
    "sersem",
    "şerefsiz",
    "sefil",
    "saygısız",
    "savunmasız",
    "sarsılmış",
    "sarhoş",
    "şanssız",
    "samimiyetsiz",
    "saldırgan",
    "sakıncalı",
    "sakar",
    "sahtekâr",
    "sahte",
    "saçma",
<<<<<<< HEAD
    "yok",
=======
>>>>>>> origin/master
    "sabırsız",
    "ruhsuz",
    "rezil",
    "psikopat",
    "pısırık",
    "pişman",
    "perişan",
    "perişan",
    "patavatsız",
    "pasaklı",
    "otistik",
    "onursuz",
    "önemsiz",
    "olgunlaşmamış",
    "öldürücü",
    "öfkeli",
    "obsesif",
    "neşesiz",
    "negatif",
    "nahoş",
    "münakaşacı",
    "muhtaç",
    "muhalif",
    "mızmız",
    "melun",
    "memnuniyetsiz",
    "melankolik",
    "megaloman",
    "mazoşist",
    "mazlum",
    "manyak",
    "mantıksız",
    "mağlup",
    "laçka",
    "küçümseyen",
    "kötümser",
    "kör",
    "kıskanç",
    "kırılgan",
    "kirli",
    "kindar",
    "kibirli",
    "ketum",
    "kederli",
    "kayıtsız",
    "kaygılı",
    "kavgacı",
<<<<<<< HEAD
    "Kasvetli"
    "saçmalık",
    "saçmalığa"
=======
    "Kasvetli",
>>>>>>> origin/master
]}







def getTweets(keyword):

    consumer_key = "ngErOW7vi7uq8TB5zfhN3YFnr"
    consumer_secret = "t2LyashkAlAn30bDQuljButNepwaUSzJlyjG0ZqzBvWxJWiNN5"
    access_token = "737548134-mOsOvlDEl38PS9zDmVtp9EeHYdbm8e3dL6Nk6Hq4"
    access_token_secret = "dRQ1ietLZOo6GvdPNybd01Nb16Adaaz2Qs65crHpJScOx"
    callback_url = "https://github.com/hamdiburakdilek/Relationship-Status-Prediction-NLP"

    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)

    api = tweepy.API(auth)

    finished_Data1 = csv.writer(open("Finished_Data.csv", "wb"))
    cleaned_Data1 = csv.writer(open("Cleaned_Data.csv", "wb"))
    pure_data1 = csv.writer(open("Pure_Data.csv", "wb"))
    search = tweepy.Cursor(api.search, q=keyword)

    for tweet in search.items():
        pure_data1.writerow([tweet.text.encode("utf8")])
        cleanedData = cleanData(tweet.text)
        cleaned_Data1.writerow([cleanedData.encode("utf8")])
        finishedData = process(cleanedData)
<<<<<<< HEAD
        finished_Data1.writerow(finishedData)
=======
        finished_Data1.writerow([finishedData.encode("utf8")])
>>>>>>> origin/master
        print finishedData

def cleanData(string):

    new_string = ''
    for i in string.split():
        s, n, p, pa, q, f = urlparse.urlparse(i)
        if s and n:
           pass
        elif i[:1] == '@':
           pass
        elif i[:2] == 'RT' :
            pass
        elif i[:1] == '#':
            new_string = new_string.strip() + ' ' + i[1:]
<<<<<<< HEAD
        elif i[:1] == "'" :
            new_string = new_string.strip() + ' ' + i[1:]
        elif i[:1] == "\"" :
            new_string = new_string.strip() + ' ' + i[1:]
=======
>>>>>>> origin/master
        else:
           new_string = new_string.strip() + ' ' + i
    return new_string

def grade(text):
    a = 0
    splitedText = text.split()

    for i in splitedText :
        for j in seslenisKelimeleri['positive'] :
            if j == i :
                a += 5
        for j in seslenisKelimeleri['negative'] :
            if j == i :
                a -= 5
        for j in sifatlar['positive'] :
            if j == i :
                a += 4
        for j in sifatlar['negative'] :
            if j == i :
                a -= 4
    return a

def process(text) :


    if grade(text) > 0 :
<<<<<<< HEAD
        ptext = ["\""+text.encode("utf8")+"\"","Positive"]
        return ptext

    else:
        ntext = ["\""+text.encode("utf8")+"\"" ,"Negative"]
=======
        ptext = '[Positive] ['+text+']'
        return ptext

    else:
        ntext = '[Negative] ['+text+']'
>>>>>>> origin/master
        return ntext

if __name__ == '__main__':
	getTweets('sevgilim')
